# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data_pb2 as data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasks.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0btasks.proto\x1a\ndata.proto\"%\n\rTasksResponse\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Taskb\x06proto3')
  ,
  dependencies=[data__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TASKSRESPONSE = _descriptor.Descriptor(
  name='TasksResponse',
  full_name='TasksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='TasksResponse.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=64,
)

_TASKSRESPONSE.fields_by_name['tasks'].message_type = data__pb2._TASK
DESCRIPTOR.message_types_by_name['TasksResponse'] = _TASKSRESPONSE

TasksResponse = _reflection.GeneratedProtocolMessageType('TasksResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKSRESPONSE,
  __module__ = 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:TasksResponse)
  ))
_sym_db.RegisterMessage(TasksResponse)


# @@protoc_insertion_point(module_scope)
